### ISSUE TITLE
Bug: Sticky not installing, might be the same problem with Deskreen

### ISSUE THREAD

**Issue by Crilum** [raspbian-addons/raspbian-addons#118]
I installed the apt repository, and ran `sudo apt install sticky`, but it says:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 sticky : Depends: gir1.2-xapp-1.0 (>= 2.2.0) but it is not going to be installed
          Depends: python3-xapp (>= 2.2.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

So I try `sudo apt install python3-xapp gir1.2-xapp sticky`, but it still has the same output..

I think this might be the same problem as the one with Deskreen that I have in my Deskreen Pi-Apps [PR](https://github.com/Botspot/pi-apps/pull/1094).

**Comment by ryanfortner** [comment]
@Crilum could you run `cat /etc/os-release` and send the output please?

**Comment by Crilum** [comment]
Here:
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by ryanfortner** [comment]
Ok, I'll take a look at it shortly.

**Comment by ryanfortner** [comment]
@Crilum could you try installing this deb please? If it works, i'll push it to the repository

http://transfer.sh/get/52ksJ6/sticky_1.0_all.deb

**Comment by Crilum** [comment]
Installs successfully, but when run:
```
$ sticky
Traceback (most recent call last):
  File "/usr/lib/sticky/sticky.py", line 15, in <module>
    from xapp.GSettingsWidgets import *
ModuleNotFoundError: No module named 'xapp.GSettingsWidgets'
```

**Comment by Crilum** [comment]
If you get it to work, I can make a Pi-Apps PR for it, if you want.

**Comment by ryanfortner** [comment]
@Crilum do you have python3-xapp installed (at least version 1.6.0)?

**Comment by Crilum** [comment]
Well, I have it installed but its version is 1.2.0-2.. Latest version of RPiOS.
```
sudo apt install python3-xapp
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-xapp is already the newest version (1.2.0-2).
python3-xapp set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by ryanfortner** [comment]
> Well, I have it installed but its version is 1.2.0-2.. Latest version of RPiOS.

Hmm... I'll test this version from Debian bullseye in a bit. 

http://ftp.us.debian.org/debian/pool/main/p/python-xapp/python3-xapp_2.0.2-2_all.deb

**Comment by Crilum** [comment]
After installing the new xapp deb, I get this:
```
$ sticky
Traceback (most recent call last):
  File "/usr/lib/sticky/sticky.py", line 603, in do_activate
    self.create_status_icon()
  File "/usr/lib/sticky/sticky.py", line 683, in create_status_icon
    self.status_icon = XApp.StatusIcon()
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 39, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 132, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.XApp' object has no attribute 'StatusIcon'

```

**Comment by ryanfortner** [comment]
Okay, at this point, I'm going to close this issue because it's an issue with the software itself, and not the repository.

To continue the discussion, i've opened an issue on the official repository: https://github.com/linuxmint/sticky/issues/42
