### ISSUE TITLE
[todo] package Mockoon

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#54]
Mockoon is the easiest and quickest way to run mock APIs locally. No remote deployment, no account required, open source.
https://github.com/mockoon/mockoon
![943C4243-D8AE-47E4-B5AF-7AA06C49CD38](https://user-images.githubusercontent.com/42692274/121814572-5a806980-cca4-11eb-8599-8ac31e9c82b1.png)

Licensing: MIT

There is a deb package here. But I don't know whether it supports arm.
https://github.com/mockoon/mockoon/releases/download/v1.14.1/mockoon-1.14.1.deb

**Comment by chunky-milk** [comment]
The deb does not support arm.

Also, just for future reference these are the steps you can use to find the architecture a deb file is for:

```bash
wget <deb link>
ar x <deb file name>
tar -xvf control.tar.gz
cat control
```
If the `Architecture` line isn't `armhf`, `armel`, or `arm64`, then the deb is not compatible with arm.

**Comment by Itai-Nelken** [comment]
The architecture line might also be `all`.

**Comment by hmsjy2017** [comment]
@chunky-milk I found a more convenient way. Just use the dpkg --info command. like this:
![EAADC263-E839-4501-B915-6A73C9CD13B5](https://user-images.githubusercontent.com/42692274/121909152-40a45c80-cd60-11eb-8403-aa6c81a70801.png)

**Comment by ryanfortner** [comment]
@hmsjy2017 any progress?

**Comment by ryanfortner** [comment]
I tried compiling on my armv7l pi, here is the output:

```
pi@piserver:~/mockoon $ npx electron-builder --linux --arm64
  • electron-builder  version=22.14.5 os=5.10.63-v7l+
  • loaded configuration  file=/home/pi/mockoon/electron-builder.json
  • writing effective config  file=packages/builder-effective-config.yaml
  • packaging       platform=linux arch=arm64 electron=13.5.2 appOutDir=packages/linux-arm64-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v13.5.2/electron-v13.5.2-linux-arm64.zip size=83 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v13.5.2/electron-v13.5.2-linux-arm64.zip duration=4.329s
  ⨯ Application entry file "dist/app.js" in the "/home/pi/mockoon/packages/linux-arm64-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file "dist/app.js" in the "/home/pi/mockoon/packages/linux-arm64-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/home/pi/mockoon/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
    at Object.checkFileInArchive (/home/pi/mockoon/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:31:11)
    at LinuxPackager.checkFileInPackage (/home/pi/mockoon/node_modules/app-builder-lib/src/platformPackager.ts:501:7)
    at LinuxPackager.sanityCheckPackage (/home/pi/mockoon/node_modules/app-builder-lib/src/platformPackager.ts:549:5)
    at LinuxPackager.doPack (/home/pi/mockoon/node_modules/app-builder-lib/src/platformPackager.ts:310:5)
    at LinuxPackager.pack (/home/pi/mockoon/node_modules/app-builder-lib/src/platformPackager.ts:136:5)
    at Packager.doBuild (/home/pi/mockoon/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/home/pi/mockoon/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/home/pi/mockoon/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/home/pi/mockoon/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/home/pi/mockoon/node_modules/builder-util/src/promise.ts:12:14)
```
